version: "2"
services:
  webserver:
    image: mydemophpimage
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DB_CONNECTION: test
      MYSQL_DB_NAME: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      SITE_URL: http://localhost
    command: php -S 0.0.0.0:8000  /var/www/html/public/index.php
  db:
    image: mysql

    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
