version: "2"
services:
  webserver:
    image: mydemophpimage
    ports:
      - "8000:8000"
      - "443:443"
    volumes:
      - .:/var/www/html
    environment:
      SITE_URL: http://localhost
    command: php -S 0.0.0.0:8000 /var/www/html/public/index.php
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: daoudi
      MYSQL_DATABASE: dbFramework
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
